### ISSUE TITLE
Am I doing something wrong?

### ISSUE THREAD

**Issue by wisdomtooth** [Darren-McConnell/YTMusicDuplicates#1]
I've gotten this far:
```
    Traceback (most recent call last):
      File "remove_dupes.py", line 105, in <module>
        main()
      File "remove_dupes.py", line 77, in main
        playlists = ytmusic.get_library_playlists(PLAYLIST_LIMIT)
      File "C:\Users\andre\AppData\Local\Programs\Python\Python38-32\lib\site-packages\ytmusicapi\ytmusic.py", line 486, in get_library_playlists
        get_continuations(results, 'gridContinuation', 25, limit, request_func,
      File "C:\Users\andre\AppData\Local\Programs\Python\Python38-32\lib\site-packages\ytmusicapi\parsers.py", line 305, in get_continuations
        items.extend(parse_func(results[continuation_contents]))
    KeyError: 'items'`
```

**Comment by wisdomtooth** [comment]
Resolved running `YTMusic.setup(filepath="headers_auth.json")` with added quotes.
